'use client'
import Link from 'next/link'
import { useUser, useClerk } from '@clerk/nextjs'
import { useState } from 'react'

const S = {
  navy:      '#0A0E1E',
  navyMid:   '#111827',
  navyLight: '#1B2A6B',
  gold:      '#D4AF37',
  red:       '#B22234',
  white:     '#FFFFFF',
  offWhite:  '#F0EDE4',
  gray:      '#8892A4',
  grayLight: '#B0BAC8',
  cardBg:    'rgba(27,42,107,0.25)',
  border:    'rgba(212,175,55,0.15)',
}

const FREE_FEATURES = [
  { icon: '🏛️', label: 'Browse all federal representatives' },
  { icon: '⚖️', label: 'Full voting record history' },
  { icon: '💰', label: 'STOCK Act trade disclosures' },
  { icon: '📋', label: "Today's congressional docket" },
  { icon: '📍', label: 'Town halls & scheduled events' },
  { icon: '💼', label: 'Wealth & financial disclosures' },
  { icon: '🏦', label: 'Nonprofit affiliations (ProPublica)' },
  { icon: '🤖', label: 'AI Analysis — free preview paragraph' },
  { icon: '🗺️', label: 'Interactive congressional district map' },
  { icon: '📜', label: 'U.S. Constitution reference' },
]

const PRO_FEATURES = [
  {
    icon: '🤖',
    title: 'Full AI Accountability Reports',
    desc: 'Complete nonpartisan AI analysis of every representative: voting pattern breakdown, trade conflict scoring, wealth trajectory vs. peers, and an overall accountability rating — not just a preview paragraph.',
  },
  {
    icon: '🔍',
    title: 'Trade Conflict Analysis',
    desc: 'Deep-dive into stock trades cross-referenced against committee assignments and pending legislation. See which trades raise questions about information asymmetry.',
  },
  {
    icon: '📈',
    title: 'Wealth Trajectory',
    desc: 'See how a representative\'s net worth has grown relative to their years in office and congressional peers — context that free data alone doesn\'t provide.',
  },
  {
    icon: '🔍',
    title: 'Peer Standing Breakdown',
    desc: 'Compare any representative\'s voting record, trade activity, and wealth accumulation against their own party and across the full chamber.',
  },
  {
    icon: '🔔',
    title: 'Track My Rep™ Alerts',
    desc: 'Get live notifications whenever any representative you\'re tracking casts a vote, files a trade disclosure, or schedules a town hall.',
  },
  {
    icon: '📍',
    title: 'State & Local Representative Lookup',
    desc: 'Enter your home address or ZIP to instantly surface your state senators, state house members, and local officials alongside your federal reps.',
  },
  {
    icon: '⭐',
    title: 'Track Any Representative',
    desc: 'Save representatives to your personal watchlist. Your tracked reps appear front and center every time you open CivicWatch.',
  },
]

const FAQS = [
  {
    q: 'Can I cancel anytime?',
    a: 'Yes. You can cancel your Pro subscription at any time from the billing portal — no cancellation fees, no gotchas. Your Pro access continues until the end of the billing period you already paid for.',
  },
  {
    q: 'What happens to my tracked representatives if I cancel?',
    a: 'Your tracking list and alert history are preserved. If you resubscribe, everything picks up where you left off. If you remain on the free tier, you\'ll simply lose access to Pro-only features like full AI reports — your account and data stay intact.',
  },
  {
    q: 'Is the $9.99/mo charge monthly or annual?',
    a: 'Monthly. There is no annual plan at this time. You\'re charged $9.99 at the start of each billing cycle.',
  },
  {
    q: 'What payment methods are accepted?',
    a: 'All major credit and debit cards (Visa, Mastercard, Amex, Discover) via Stripe. Apple Pay and Google Pay are also supported where available.',
  },
  {
    q: 'Is CivicWatch data nonpartisan?',
    a: 'Yes. CivicWatch pulls from official government sources — congressional voting records, SEC/STOCK Act filings, FEC campaign finance data, and official financial disclosures. The AI Analysis is explicitly prompted for nonpartisan framing and covers representatives across both parties equally.',
  },
  {
    q: 'Where does the data come from?',
    a: 'Federal voting records come from the official congressional API. Trade disclosures come from House and Senate financial disclosure systems. Wealth data comes from official financial disclosure filings. AI reports are generated by Google Gemini and are for informational purposes only — not legal or financial advice.',
  },
  {
    q: 'Do you store my home address?',
    a: 'Your address lookup is used only to find your representatives in real time — it is not stored in our database beyond your browser session.',
  },
]

export default function ProPage() {
  const { user, isSignedIn } = useUser()
  const { openSignIn } = useClerk()
  const isPro = user?.publicMetadata?.isPro === true
  const [openFaq, setOpenFaq] = useState(null)
  const [loading, setLoading] = useState(false)

  const handleUpgrade = async () => {
    if (!isSignedIn) { openSignIn(); return }
    setLoading(true)
    try {
      const res = await fetch('/api/subscribe', { method: 'POST' })
      const { url } = await res.json()
      if (url) window.location.href = url
    } catch (e) {
      console.error('Subscribe error:', e)
    } finally {
      setLoading(false)
    }
  }

  const handleBillingPortal = async () => {
    setLoading(true)
    try {
      const res = await fetch('/api/billing-portal', { method: 'POST' })
      const { url } = await res.json()
      if (url) window.location.href = url
    } catch (e) {
      console.error('Billing portal error:', e)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{ fontFamily: "'Source Serif 4', Georgia, serif", background: S.navy, minHeight: '100vh', color: S.white, overflowX: 'hidden' }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=Source+Serif+4:wght@300;400;600&display=swap');
        *, *::before, *::after { box-sizing: border-box; }
        html, body { margin: 0; padding: 0; }
        .star-pattern { background-image: radial-gradient(circle, rgba(212,175,55,0.08) 1px, transparent 1px); background-size: 24px 24px; }
        .pro-card { background: linear-gradient(145deg, rgba(27,42,107,0.6), rgba(10,14,30,0.9)); border: 1px solid ${S.border}; border-radius: 16px; padding: 24px; transition: transform 0.2s, box-shadow 0.2s; }
        .pro-card:hover { transform: translateY(-2px); box-shadow: 0 12px 40px rgba(212,175,55,0.12); }
        .faq-item { border-bottom: 1px solid ${S.border}; }
        .faq-q { width: 100%; background: none; border: none; color: ${S.white}; font-family: inherit; font-size: 15px; font-weight: 600; text-align: left; padding: 20px 0; cursor: pointer; display: flex; justify-content: space-between; align-items: center; gap: 16px; }
        .faq-a { font-size: 14px; color: ${S.grayLight}; line-height: 1.8; padding-bottom: 20px; }
        .cta-btn { padding: 16px 40px; background: linear-gradient(135deg, ${S.gold}, #B8960C); border: none; border-radius: 12px; color: ${S.navy}; font-family: inherit; font-size: 16px; font-weight: 700; cursor: pointer; letter-spacing: 0.5px; transition: opacity 0.2s, transform 0.15s; }
        .cta-btn:hover { opacity: 0.92; transform: translateY(-1px); }
        .cta-btn:disabled { opacity: 0.6; cursor: not-allowed; transform: none; }
        .free-pill { display: inline-flex; align-items: center; gap: 8px; padding: 8px 16px; background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.1); border-radius: 30px; font-size: 13px; color: ${S.grayLight}; }
        .check { color: #4CAF50; font-size: 14px; flex-shrink: 0; }
        @media (max-width: 768px) {
          .comparison-grid { grid-template-columns: 1fr !important; }
          .hero-title { font-size: 36px !important; }
          .section-pad { padding: 60px 20px !important; }
          .pro-features-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>

      {/* ── NAV ── */}
      <header style={{ borderBottom: `1px solid ${S.border}`, padding: '0 24px', height: 60, display: 'flex', alignItems: 'center', justifyContent: 'space-between', position: 'sticky', top: 0, background: `rgba(10,14,30,0.95)`, backdropFilter: 'blur(12px)', zIndex: 100 }}>
        <Link href="/" style={{ fontFamily: "'Playfair Display', serif", fontWeight: 900, fontSize: 18, color: S.white, textDecoration: 'none', letterSpacing: 0.5 }}>
          🏛️ CivicWatch
        </Link>
        <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <Link href="/dashboard" style={{ fontSize: 13, color: S.gray, textDecoration: 'none' }}>← Back to Dashboard</Link>
          {isPro && (
            <button onClick={handleBillingPortal} style={{ padding: '7px 14px', background: `rgba(212,175,55,0.12)`, border: `1px solid ${S.gold}`, borderRadius: 8, color: S.gold, fontSize: 11, fontWeight: 700, fontFamily: 'inherit', cursor: 'pointer' }}>
              ★ Pro Member — Manage
            </button>
          )}
        </div>
      </header>

      {/* ── HERO ── */}
      <section className="section-pad" style={{ padding: '80px 24px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
        <div className="star-pattern" style={{ position: 'absolute', inset: 0, opacity: 0.5 }} />
        <div style={{ position: 'relative', maxWidth: 760, margin: '0 auto' }}>
          <div style={{ display: 'inline-block', padding: '5px 16px', background: `rgba(212,175,55,0.12)`, border: `1px solid ${S.gold}`, borderRadius: 30, fontSize: 12, color: S.gold, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 24 }}>
            CivicWatch Pro
          </div>
          <h1 className="hero-title" style={{ fontFamily: "'Playfair Display', serif", fontWeight: 900, fontSize: 52, lineHeight: 1.15, margin: '0 0 20px' }}>
            Accountability at the<br />depth it deserves.
          </h1>
          <p style={{ fontSize: 18, color: S.grayLight, lineHeight: 1.7, margin: '0 0 40px', maxWidth: 560, marginLeft: 'auto', marginRight: 'auto' }}>
            CivicWatch Pro unlocks full AI analysis, trade conflict scoring, wealth trajectories, real-time alerts, and local representative lookup — everything you need to hold your elected officials accountable.
          </p>

          {isPro ? (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
              <div style={{ padding: '14px 32px', background: `rgba(212,175,55,0.12)`, border: `1px solid ${S.gold}`, borderRadius: 12, color: S.gold, fontSize: 16, fontWeight: 700 }}>
                ★ You're a Pro Member
              </div>
              <button onClick={handleBillingPortal} disabled={loading} style={{ fontSize: 13, color: S.gray, background: 'none', border: 'none', cursor: 'pointer', fontFamily: 'inherit', textDecoration: 'underline' }}>
                Manage billing →
              </button>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 14 }}>
              <button className="cta-btn" onClick={handleUpgrade} disabled={loading}>
                {loading ? 'Redirecting…' : '★ Go Pro — $9.99/mo'}
              </button>
              <div style={{ fontSize: 12, color: S.gray }}>Cancel anytime · No contracts · Stripe-secured checkout</div>
            </div>
          )}
        </div>
      </section>

      {/* ── FREE vs PRO COMPARISON ── */}
      <section className="section-pad" style={{ padding: '80px 24px', background: `rgba(27,42,107,0.15)` }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <h2 style={{ fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 32, textAlign: 'center', marginBottom: 48, marginTop: 0 }}>
            Free vs. Pro
          </h2>
          <div className="comparison-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>
            {/* FREE */}
            <div style={{ background: S.cardBg, border: `1px solid rgba(255,255,255,0.08)`, borderRadius: 20, padding: 32 }}>
              <div style={{ marginBottom: 24 }}>
                <div style={{ fontSize: 12, letterSpacing: 2, textTransform: 'uppercase', color: S.gray, marginBottom: 8 }}>Free</div>
                <div style={{ fontFamily: "'Playfair Display', serif", fontSize: 28, fontWeight: 700 }}>$0</div>
                <div style={{ fontSize: 13, color: S.gray, marginTop: 4 }}>No credit card required</div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {FREE_FEATURES.map(f => (
                  <div key={f.label} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                    <span className="check">✓</span>
                    <span style={{ fontSize: 14, color: S.grayLight }}><span style={{ marginRight: 6 }}>{f.icon}</span>{f.label}</span>
                  </div>
                ))}
              </div>
              <div style={{ marginTop: 28 }}>
                <Link href="/dashboard" style={{ display: 'block', textAlign: 'center', padding: '12px 24px', background: 'rgba(255,255,255,0.06)', border: `1px solid rgba(255,255,255,0.12)`, borderRadius: 10, color: S.offWhite, fontSize: 14, fontWeight: 600, textDecoration: 'none' }}>
                  Open Dashboard →
                </Link>
              </div>
            </div>

            {/* PRO */}
            <div style={{ background: `linear-gradient(145deg, rgba(27,42,107,0.7), rgba(10,14,30,0.95))`, border: `1px solid ${S.gold}`, borderRadius: 20, padding: 32, position: 'relative', overflow: 'hidden' }}>
              <div className="star-pattern" style={{ position: 'absolute', inset: 0, opacity: 0.3 }} />
              <div style={{ position: 'relative' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 }}>
                  <div>
                    <div style={{ fontSize: 12, letterSpacing: 2, textTransform: 'uppercase', color: S.gold, marginBottom: 8 }}>Pro</div>
                    <div style={{ fontFamily: "'Playfair Display', serif", fontSize: 28, fontWeight: 700 }}>$9.99<span style={{ fontSize: 14, fontWeight: 400, color: S.gray }}>/mo</span></div>
                    <div style={{ fontSize: 13, color: S.gray, marginTop: 4 }}>Cancel anytime</div>
                  </div>
                  <div style={{ padding: '4px 12px', background: `rgba(212,175,55,0.15)`, border: `1px solid ${S.gold}`, borderRadius: 20, fontSize: 11, color: S.gold, fontWeight: 700 }}>BEST VALUE</div>
                </div>
                <div style={{ fontSize: 13, color: S.gray, marginBottom: 16 }}>Everything in Free, plus:</div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                  {PRO_FEATURES.map(f => (
                    <div key={f.title} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                      <span style={{ color: S.gold, fontSize: 14, flexShrink: 0 }}>★</span>
                      <div>
                        <div style={{ fontSize: 14, fontWeight: 600, color: S.offWhite }}>{f.icon} {f.title}</div>
                      </div>
                    </div>
                  ))}
                </div>
                <div style={{ marginTop: 28 }}>
                  {isPro ? (
                    <button onClick={handleBillingPortal} disabled={loading} style={{ width: '100%', padding: '13px 24px', background: `rgba(212,175,55,0.12)`, border: `1px solid ${S.gold}`, borderRadius: 10, color: S.gold, fontSize: 14, fontWeight: 700, fontFamily: 'inherit', cursor: 'pointer' }}>
                      ★ Manage Pro Subscription
                    </button>
                  ) : (
                    <button className="cta-btn" onClick={handleUpgrade} disabled={loading} style={{ width: '100%', padding: '13px 24px', fontSize: 14 }}>
                      {loading ? 'Redirecting…' : '★ Go Pro — $9.99/mo'}
                    </button>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── PRO FEATURE DEEP-DIVES ── */}
      <section className="section-pad" style={{ padding: '80px 24px' }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <h2 style={{ fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 32, textAlign: 'center', marginBottom: 12, marginTop: 0 }}>
            What Pro unlocks
          </h2>
          <p style={{ textAlign: 'center', color: S.gray, fontSize: 15, marginBottom: 48, marginTop: 0 }}>
            Every Pro feature is built on real government data — not estimates or approximations.
          </p>
          <div className="pro-features-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}>
            {PRO_FEATURES.map(f => (
              <div key={f.title} className="pro-card">
                <div style={{ fontSize: 28, marginBottom: 12 }}>{f.icon}</div>
                <div style={{ fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 18, marginBottom: 10, color: S.offWhite }}>{f.title}</div>
                <div style={{ fontSize: 13, color: S.grayLight, lineHeight: 1.75 }}>{f.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── SOCIAL PROOF / MISSION ── */}
      <section className="section-pad" style={{ padding: '80px 24px', background: `rgba(27,42,107,0.2)`, textAlign: 'center' }}>
        <div style={{ maxWidth: 640, margin: '0 auto' }}>
          <div style={{ fontSize: 36, marginBottom: 20 }}>🇺🇸</div>
          <h2 style={{ fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 28, marginBottom: 16, marginTop: 0 }}>
            Why CivicWatch Pro exists
          </h2>
          <p style={{ fontSize: 15, color: S.grayLight, lineHeight: 1.85, marginBottom: 20 }}>
            Government financial disclosures are public record — but they're buried in PDFs, scattered across systems, and nearly impossible to cross-reference at scale. CivicWatch Pro aggregates all of it and runs AI analysis so you don't have to spend hours doing it yourself.
          </p>
          <p style={{ fontSize: 15, color: S.grayLight, lineHeight: 1.85, marginBottom: 32 }}>
            Your $9.99/mo keeps the servers running, the data updated, and the AI models paid for. No ads, no data brokering, no sponsored content — just the data.
          </p>
          {!isPro && (
            <button className="cta-btn" onClick={handleUpgrade} disabled={loading}>
              {loading ? 'Redirecting…' : '★ Go Pro — $9.99/mo'}
            </button>
          )}
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className="section-pad" style={{ padding: '80px 24px' }}>
        <div style={{ maxWidth: 720, margin: '0 auto' }}>
          <h2 style={{ fontFamily: "'Playfair Display', serif", fontWeight: 700, fontSize: 32, textAlign: 'center', marginBottom: 40, marginTop: 0 }}>
            Frequently asked questions
          </h2>
          <div>
            {FAQS.map((faq, i) => (
              <div key={i} className="faq-item">
                <button className="faq-q" onClick={() => setOpenFaq(openFaq === i ? null : i)}>
                  <span>{faq.q}</span>
                  <span style={{ color: S.gold, fontSize: 18, flexShrink: 0 }}>{openFaq === i ? '−' : '+'}</span>
                </button>
                {openFaq === i && (
                  <div className="faq-a">{faq.a}</div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── BOTTOM CTA ── */}
      {!isPro && (
        <section className="section-pad" style={{ padding: '80px 24px', background: `linear-gradient(135deg, rgba(27,42,107,0.6), rgba(10,14,30,0.95))`, textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
          <div className="star-pattern" style={{ position: 'absolute', inset: 0, opacity: 0.4 }} />
          <div style={{ position: 'relative', maxWidth: 560, margin: '0 auto' }}>
            <h2 style={{ fontFamily: "'Playfair Display', serif", fontWeight: 900, fontSize: 36, marginBottom: 16, marginTop: 0 }}>
              Ready to go deeper?
            </h2>
            <p style={{ fontSize: 15, color: S.grayLight, marginBottom: 32, lineHeight: 1.7 }}>
              Join CivicWatch Pro and get the full picture on every representative in Congress.
            </p>
            <button className="cta-btn" onClick={handleUpgrade} disabled={loading} style={{ fontSize: 17, padding: '18px 48px' }}>
              {loading ? 'Redirecting…' : '★ Go Pro — $9.99/mo'}
            </button>
            <div style={{ marginTop: 16, fontSize: 12, color: S.gray }}>Cancel anytime · Stripe-secured · No ads ever</div>
          </div>
        </section>
      )}

      {/* ── FOOTER ── */}
      <footer style={{ borderTop: `1px solid ${S.border}`, padding: '24px', textAlign: 'center', fontSize: 12, color: S.gray }}>
        <div style={{ marginBottom: 12 }}>
          <Link href="/dashboard" style={{ color: S.gray, textDecoration: 'none', marginRight: 20 }}>Dashboard</Link>
          <Link href="/privacy" style={{ color: S.gray, textDecoration: 'none', marginRight: 20 }}>Privacy</Link>
          <Link href="/terms" style={{ color: S.gray, textDecoration: 'none' }}>Terms</Link>
        </div>
        <div>© {new Date().getFullYear()} CivicWatch · For informational purposes only · Not legal or financial advice</div>
      </footer>
    </div>
  )
}
